FROM cassiorp23/wso2ubuntu:latest

# Copiar o arquivo .car
COPY /CAR_APIs/AtendimentoComorbidadeCompositeExporter_1.0.0.car /wso2mi-4.2.0/repository/deployment/server/carbonapps

# Definir a porta de binding
EXPOSE 9202 9165 8291 8254

# Comando de inicialização do Micro Integrator
CMD /wso2mi-4.2.0/bin/micro-integrator.sh -DenablePrometheusApi=true -DportOffset=11 -DenableManagementApi=true
